name: Lint Code

on:
  # Trigger the workflow on push or pull request, but only for the main branch.
  # Don't use pull_request.paths filter since this workflow is required for
  # all pull requests on main irrespective of file type or location.
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - pyproject.toml
      - .github/workflows/matchers/ruff.json
      - .github/workflows/lint_code.yml

jobs:
  lint-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --frozen --only-group lint
      - name: Analysing the code with ruff
        run: |
          echo "::add-matcher::.github/workflows/matchers/ruff.json"
          ruff check --output-format github .
      - name: Run isort
        # using `always()` here ensures all the checks run even if previous
        # checks fail
        if: always()
        run: isort . --check-only
      - name: run yapf
        if: always()
        run: yapf --diff --recursive .
      - name: Spelling check with codespell
        if: always()
        run: codespell --toml pyproject.toml

